insert_tail = """);"""

insert_body = """) VALUES ("""

insert_head = """INSERT INTO %s ("""

LOAN_TABLE_CREATION_QUERY = """
CREATE TABLE IF NOT EXISTS all_tb (
    id NUMERIC NOT NULL PRIMARY KEY,
    member_id NUMERIC,
    loan_amnt NUMERIC,
    funded_amnt NUMERIC,
    funded_amnt_inv NUMERIC,
    term VARCHAR(10),
    int_rate NUMERIC,
    installment NUMERIC,
    grade VARCHAR(1),
    sub_grade VARCHAR(2),
    emp_title VARCHAR(40),
    emp_length VARCHAR(9),
    home_ownership VARCHAR(8),
    annual_inc NUMERIC,
    verification_status VARCHAR(15),
    issue_d VARCHAR(6),
    loan_status VARCHAR(11),
    pymnt_plan VARCHAR(1),
    url VARCHAR(69),
    "desc" VARCHAR(2002),
    purpose VARCHAR(18),
    title VARCHAR(40),
    zip_code VARCHAR(5),
    addr_state VARCHAR(2),
    dti NUMERIC,
    delinq_2yrs NUMERIC,
    earliest_cr_line VARCHAR(6),
    inq_last_6mths NUMERIC,
    mths_since_last_delinq NUMERIC,
    mths_since_last_record NUMERIC,
    open_acc NUMERIC,
    pub_rec NUMERIC,
    revol_bal NUMERIC,
    revol_util NUMERIC,
    total_acc NUMERIC,
    initial_list_status VARCHAR(1),
    out_prncp NUMERIC,
    out_prncp_inv NUMERIC,
    total_pymnt NUMERIC,
    total_pymnt_inv NUMERIC,
    total_rec_prncp NUMERIC,
    total_rec_int NUMERIC,
    total_rec_late_fee NUMERIC,
    recoveries NUMERIC,
    collection_recovery_fee NUMERIC,
    last_pymnt_d VARCHAR(6),
    last_pymnt_amnt NUMERIC,
    next_pymnt_d VARCHAR(6),
    last_credit_pull_d VARCHAR(6),
    collections_12_mths_ex_med NUMERIC,
    mths_since_last_major_derog NUMERIC,
    policy_code NUMERIC,
    application_type VARCHAR(10),
    annual_inc_joint NUMERIC,
    dti_joint NUMERIC,
    verification_status_joint VARCHAR(12),
    acc_now_delinq NUMERIC,
    tot_coll_amt NUMERIC,
    tot_cur_bal NUMERIC,
    open_acc_6m NUMERIC,
    open_il_6m NUMERIC,
    open_il_12m NUMERIC,
    open_il_24m NUMERIC,
    mths_since_rcnt_il NUMERIC,
    total_bal_il NUMERIC,
    il_util NUMERIC,
    open_rv_12m NUMERIC,
    open_rv_24m NUMERIC,
    max_bal_bc NUMERIC,
    all_util NUMERIC,
    total_rev_hi_lim NUMERIC,
    inq_fi NUMERIC,
    total_cu_tl NUMERIC,
    inq_last_12m NUMERIC
);
"""
